MSG_VERSION=1.0
APP_ID=KARZA
TOKEN=37f21104-ec7b-4c64-b7d7-600550597d9b
API_SERVICE_LOGOUT_IN_SEC=100
PAN_VERI_URL=http://10.1.2.117:8080/ibs/ib/karza/api/v2/requestKarzaPan
GST_FROM_PAN_URL=http://10.1.2.117:8080/ibs/ib/karza/api/v1/requestKarzaGSTSearchPan
GST_ADDRESS_REQ_URL=http://10.1.2.117:8080/ibs/ib/karza/api/v1/requestKarzaGspGstinAuth
GST_ADDRESS_SPLIT_URL=http://10.1.2.117:8080/ibs/ib/karza/api/v2/AddressSplit
KARZA_PANGST_APPLICABLE=TRUE
AADHAAR_GENERATE_OTP_URL=http://10.1.1.110:8580/ibs/ib/karza/api/v2/requestKarzaAdharOTP
AADHAAR_GENERATE_FILE_URL=http://10.1.1.110:8580/ibs/ib/karza/api/v2/requestKarzaAdharXML
IBS_VAHAN_APP_ID=VAHAN
IBS_VAHAN_TOKEN=36bba76d-d6f8-4e00-b60c-665f4b49a8e3
VAHAN_HPA_URL=http://10.1.1.110:8580/ibs/ib/vahan/api/v2/vahanHPA/
VAHAN_HPC_URL=http://10.1.1.110:8580/ibs/ib/vahan/api/v2/vahanHPC/
VAHAN_HPT_URL=http://10.1.4.118:12860/ibs/ib/vahan/api/v2/vahanHPT/
#PASSPORT_VERIFY_URL=http://10.1.2.117:8480/ibs/ib/karza/api/v3/requestKarzaPassport
#DL_VERI_URL=http://10.1.2.117:8480/ibs/ib/karza/api/v3/requestKarzaDL
#VERIFY_VOTER_URL=http://10.1.2.117:8480/ibs/ib/karza/api/v2/requestKarzaVoter
PASSPORT_VERIFY_URL=http://10.1.2.117:8580/ibs/ib/karza/api/v3/requestKarzaPassport
DL_VERI_URL=http://10.1.2.117:8580/ibs/ib/karza/api/v3/requestKarzaDL
VERIFY_VOTER_URL=http://10.1.2.117:8580/ibs/ib/karza/api/v2/requestKarzaVoter
#UDYAM_VERI_URL=http://10.1.2.117:8480/ibs/ib/karza/api/v3/udyamRegCheck
UDYAM_VERI_URL=http://10.1.2.117:8580/ibs/ib/karza/api/v3/udyamRegCheck
QUOTATION_VALIDATION_DESIGNATION=Y

# Keystore Vault Configurations
KEY_STORE_PATH=/opt/jboss/wildfly/bin/vault/vault.keystore
KEY_STORE_PASSWORD = MASK-3b3EDyX4/WwVjxExoF1CsN
VAULT_BLOCK = ds_OracleDS
ATTRIBUTE_NAME_QC_USER_AUTH=password-4
ATTRIBUTE_NAME_QC_PROSPECT=password-8
ATTRIBUTE_NAME_QC_MASTER=password-1
SALT = 1234abcd
INT_COUNT = 120
KEYSTORE_ALIAS=vault
ENC_FILE_DIR=/opt/jboss/wildfly/bin/vault/

UCIC_APP_ID=UCIC
UCIC_TOKEN=7435c041-6646-42c2-a41d-addb820105b3
UCIC_URL= http://10.1.4.118:12798/ibs/ib/ucic/api/v1/createupdateucic
UCIC_INTEGRATION_ENABLE=N
UCIC_UTILITY_SCHEDULAR=5

INTERVAL_MINUTES=1
STATUSAPI_INTERVAL_MINUTES=1
CONNECTION_TIMEOUT=10
timeInMinute=60


HPT_SUCCESS_RESPONSE_CODE=1,112,119,116
HPT_DOC_URL=www.abc.org
